import { PrismaClient } from '@prisma/client'

export async function seedConversations(prisma: PrismaClient) {
  console.log('Seeding conversations...')

  // ─── Conversations ──────────────────────────────────────────────────────────

  const conversations = [
    { id: 'CONV001', type: 'direct', createdAt: new Date('2024-11-15T08:00:00'), updatedAt: new Date('2024-11-17T19:30:00') },
    { id: 'CONV002', type: 'direct', createdAt: new Date('2024-11-20T09:00:00'), updatedAt: new Date('2024-11-21T16:45:00') },
    { id: 'CONV003', type: 'direct', createdAt: new Date('2024-11-25T07:30:00'), updatedAt: new Date('2024-11-25T18:00:00') },
    { id: 'CONV004', type: 'direct', createdAt: new Date('2024-12-01T10:00:00'), updatedAt: new Date('2024-12-01T17:20:00') },
    { id: 'CONV005', type: 'direct', createdAt: new Date('2024-12-03T07:00:00'), updatedAt: new Date('2024-12-04T20:00:00') },
    { id: 'CONV006', type: 'direct', createdAt: new Date('2024-12-08T09:00:00'), updatedAt: new Date('2024-12-10T15:30:00') },
    { id: 'CONV007', type: 'direct', createdAt: new Date('2024-12-12T08:00:00'), updatedAt: new Date('2024-12-13T17:00:00') },
    { id: 'CONV008', type: 'direct', createdAt: new Date('2024-12-14T09:00:00'), updatedAt: new Date('2024-12-15T16:30:00') },
    { id: 'CONV009', type: 'direct', createdAt: new Date('2024-12-16T07:30:00'), updatedAt: new Date('2024-12-17T14:45:00') },
    { id: 'CONV010', type: 'direct', createdAt: new Date('2024-12-18T10:00:00'), updatedAt: new Date('2024-12-19T16:00:00') },
    { id: 'CONV011', type: 'direct', createdAt: new Date('2024-12-20T08:30:00'), updatedAt: new Date('2024-12-21T17:30:00') },
    { id: 'CONV012', type: 'direct', createdAt: new Date('2024-12-22T07:00:00'), updatedAt: new Date('2024-12-23T15:00:00') },
  ]

  for (const conv of conversations) {
    await prisma.conversation.upsert({
      where: { id: conv.id },
      update: {},
      create: conv,
    })
  }

  // ─── Participants ───────────────────────────────────────────────────────────

  const participants = [
    // CONV001: PAT001 ↔ DOC001
    { id: 'CP001', conversationId: 'CONV001', userId: 'PAT001', joinedAt: new Date('2024-11-15T08:00:00') },
    { id: 'CP002', conversationId: 'CONV001', userId: 'DOC001', joinedAt: new Date('2024-11-15T08:00:00') },
    // CONV002: PAT002 ↔ NUR001
    { id: 'CP003', conversationId: 'CONV002', userId: 'PAT002', joinedAt: new Date('2024-11-20T09:00:00') },
    { id: 'CP004', conversationId: 'CONV002', userId: 'NUR001', joinedAt: new Date('2024-11-20T09:00:00') },
    // CONV003: PAT003 ↔ NAN001
    { id: 'CP005', conversationId: 'CONV003', userId: 'PAT003', joinedAt: new Date('2024-11-25T07:30:00') },
    { id: 'CP006', conversationId: 'CONV003', userId: 'NAN001', joinedAt: new Date('2024-11-25T07:30:00') },
    // CONV004: PAT001 ↔ PHARM001
    { id: 'CP007', conversationId: 'CONV004', userId: 'PAT001', joinedAt: new Date('2024-12-01T10:00:00') },
    { id: 'CP008', conversationId: 'CONV004', userId: 'PHARM001', joinedAt: new Date('2024-12-01T10:00:00') },
    // CONV005: DOC002 ↔ NUR002
    { id: 'CP009', conversationId: 'CONV005', userId: 'DOC002', joinedAt: new Date('2024-12-03T07:00:00') },
    { id: 'CP010', conversationId: 'CONV005', userId: 'NUR002', joinedAt: new Date('2024-12-03T07:00:00') },
    // CONV006: PAT005 ↔ DOC003
    { id: 'CP011', conversationId: 'CONV006', userId: 'PAT005', joinedAt: new Date('2024-12-08T09:00:00') },
    { id: 'CP012', conversationId: 'CONV006', userId: 'DOC003', joinedAt: new Date('2024-12-08T09:00:00') },
    // CONV007: PAT001 ↔ LAB001
    { id: 'CP013', conversationId: 'CONV007', userId: 'PAT001', joinedAt: new Date('2024-12-12T08:00:00') },
    { id: 'CP014', conversationId: 'CONV007', userId: 'LAB001', joinedAt: new Date('2024-12-12T08:00:00') },
    // CONV008: PAT002 ↔ EMW001
    { id: 'CP015', conversationId: 'CONV008', userId: 'PAT002', joinedAt: new Date('2024-12-14T09:00:00') },
    { id: 'CP016', conversationId: 'CONV008', userId: 'EMW001', joinedAt: new Date('2024-12-14T09:00:00') },
    // CONV009: DOC001 ↔ PHARM001
    { id: 'CP017', conversationId: 'CONV009', userId: 'DOC001', joinedAt: new Date('2024-12-16T07:30:00') },
    { id: 'CP018', conversationId: 'CONV009', userId: 'PHARM001', joinedAt: new Date('2024-12-16T07:30:00') },
    // CONV010: PAT001 ↔ INS001
    { id: 'CP019', conversationId: 'CONV010', userId: 'PAT001', joinedAt: new Date('2024-12-18T10:00:00') },
    { id: 'CP020', conversationId: 'CONV010', userId: 'INS001', joinedAt: new Date('2024-12-18T10:00:00') },
    // CONV011: PAT003 ↔ DOC002
    { id: 'CP021', conversationId: 'CONV011', userId: 'PAT003', joinedAt: new Date('2024-12-20T08:30:00') },
    { id: 'CP022', conversationId: 'CONV011', userId: 'DOC002', joinedAt: new Date('2024-12-20T08:30:00') },
    // CONV012: NUR001 ↔ NAN001
    { id: 'CP023', conversationId: 'CONV012', userId: 'NUR001', joinedAt: new Date('2024-12-22T07:00:00') },
    { id: 'CP024', conversationId: 'CONV012', userId: 'NAN001', joinedAt: new Date('2024-12-22T07:00:00') },
  ]

  await prisma.conversationParticipant.createMany({
    data: participants,
    skipDuplicates: true,
  })

  // ─── Messages ───────────────────────────────────────────────────────────────

  const read = (dateStr: string) => new Date(dateStr)

  const messages = [
    // ═══════════════════════════════════════════════════════════════════════════
    // CONV001 — PAT001 ↔ DOC001: Diabetes management (Nov 15–17, 3 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG001', conversationId: 'CONV001', senderId: 'PAT001', content: 'Good morning Dr. Johnson. I wanted to reach out because my fasting blood sugar has been running higher than usual this past week, around 160-180 mg/dL. Should I be concerned?', readAt: read('2024-11-15T08:20:00'), createdAt: new Date('2024-11-15T08:12:00') },
    { id: 'MSG002', conversationId: 'CONV001', senderId: 'DOC001', content: 'Good morning Emma. Thank you for reaching out. Those readings are higher than our target range of 80-130 mg/dL for fasting glucose. Have there been any changes in your diet, exercise, or stress levels recently?', readAt: read('2024-11-15T08:35:00'), createdAt: new Date('2024-11-15T08:22:00') },
    { id: 'MSG003', conversationId: 'CONV001', senderId: 'PAT001', content: 'Now that you mention it, I have been under a lot of stress at work. I also skipped my evening walks the last two weeks. Could that really make such a big difference?', readAt: read('2024-11-15T08:55:00'), createdAt: new Date('2024-11-15T08:40:00') },
    { id: 'MSG004', conversationId: 'CONV001', senderId: 'DOC001', content: 'Absolutely. Stress hormones like cortisol directly raise blood sugar, and physical activity is one of the most effective ways to improve insulin sensitivity. Even a 20-minute walk after meals can significantly lower post-prandial glucose levels.', readAt: read('2024-11-15T09:10:00'), createdAt: new Date('2024-11-15T09:00:00') },
    { id: 'MSG005', conversationId: 'CONV001', senderId: 'PAT001', content: 'I did not realize stress could have that much impact. What about my diet? I have been eating more rice and bread lately because it is quicker to prepare.', readAt: read('2024-11-15T14:20:00'), createdAt: new Date('2024-11-15T14:05:00') },
    { id: 'MSG006', conversationId: 'CONV001', senderId: 'DOC001', content: 'That is likely a contributing factor. White rice and bread are high-glycemic foods that cause rapid blood sugar spikes. Try switching to brown rice, whole-grain bread, or even cauliflower rice. Pair carbohydrates with protein and healthy fats to slow absorption.', readAt: read('2024-11-15T14:50:00'), createdAt: new Date('2024-11-15T14:30:00') },
    { id: 'MSG007', conversationId: 'CONV001', senderId: 'PAT001', content: 'That makes sense. Should I adjust my Metformin dosage at all, or keep it the same for now?', readAt: read('2024-11-16T07:50:00'), createdAt: new Date('2024-11-16T07:30:00') },
    { id: 'MSG008', conversationId: 'CONV001', senderId: 'DOC001', content: 'Let us keep your Metformin at 500mg twice daily for now. I would like you to implement the lifestyle changes first and monitor your fasting glucose every morning for the next two weeks. If readings remain above 150 mg/dL consistently, we will discuss adjusting the dosage.', readAt: read('2024-11-16T08:20:00'), createdAt: new Date('2024-11-16T08:05:00') },
    { id: 'MSG009', conversationId: 'CONV001', senderId: 'PAT001', content: 'Understood. I will start logging my readings in the app. One more question — are there any snacks you would recommend between meals? I get hungry mid-afternoon and that is when I tend to reach for biscuits.', readAt: read('2024-11-16T12:30:00'), createdAt: new Date('2024-11-16T12:10:00') },
    { id: 'MSG010', conversationId: 'CONV001', senderId: 'DOC001', content: 'Great question. Try almonds, Greek yogurt, carrot sticks with hummus, or a small apple with peanut butter. These provide sustained energy without the sugar spike. Avoid packaged biscuits and fruit juices — they are loaded with hidden sugars.', readAt: read('2024-11-16T13:00:00'), createdAt: new Date('2024-11-16T12:40:00') },
    { id: 'MSG011', conversationId: 'CONV001', senderId: 'PAT001', content: 'Perfect, I will stock up on those this weekend. Should I also be worried about my HbA1c? My last reading was 7.2% about three months ago.', readAt: read('2024-11-17T09:10:00'), createdAt: new Date('2024-11-17T08:45:00') },
    { id: 'MSG012', conversationId: 'CONV001', senderId: 'DOC001', content: 'An HbA1c of 7.2% is slightly above our target of below 7%. With these lifestyle adjustments, we should be able to bring it down. I would like to recheck it in January. In the meantime, focus on consistent meals, daily walks, and stress management.', readAt: read('2024-11-17T09:40:00'), createdAt: new Date('2024-11-17T09:15:00') },
    { id: 'MSG013', conversationId: 'CONV001', senderId: 'PAT001', content: 'Thank you doctor. I feel much better having a clear plan. I will start the walks again tonight and switch to brown rice starting tomorrow.', readAt: read('2024-11-17T10:00:00'), createdAt: new Date('2024-11-17T09:50:00') },
    { id: 'MSG014', conversationId: 'CONV001', senderId: 'DOC001', content: 'Excellent attitude Emma. Remember, small consistent changes are more sustainable than drastic ones. Keep logging your readings and do not hesitate to message me if your numbers do not start improving within a week.', readAt: read('2024-11-17T10:20:00'), createdAt: new Date('2024-11-17T10:05:00') },
    { id: 'MSG015', conversationId: 'CONV001', senderId: 'PAT001', content: 'Will do. Also, is it okay to have a small piece of dark chocolate occasionally? I have read it may actually help with blood sugar.', readAt: read('2024-11-17T18:30:00'), createdAt: new Date('2024-11-17T18:10:00') },
    { id: 'MSG016', conversationId: 'CONV001', senderId: 'DOC001', content: 'Dark chocolate with at least 70% cocoa is fine in moderation — a small square or two after a meal. It contains flavonoids that may improve insulin sensitivity. Just watch the portion size and avoid milk chocolate varieties.', readAt: read('2024-11-17T19:00:00'), createdAt: new Date('2024-11-17T18:40:00') },
    { id: 'MSG017', conversationId: 'CONV001', senderId: 'PAT001', content: 'That is great news! Thank you so much for all the guidance, Dr. Johnson. I will follow up in two weeks with my glucose log.', readAt: null, createdAt: new Date('2024-11-17T19:10:00') },
    { id: 'MSG018', conversationId: 'CONV001', senderId: 'DOC001', content: 'You are welcome. Take care and stay consistent. Looking forward to seeing those improved numbers!', readAt: null, createdAt: new Date('2024-11-17T19:25:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV002 — PAT002 ↔ NUR001: Post-surgery care (Nov 20–21, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG019', conversationId: 'CONV002', senderId: 'PAT002', content: 'Hello, I just got home from the hospital after my appendectomy yesterday. The discharge instructions mentioned wound care but I want to make sure I am doing everything correctly.', readAt: read('2024-11-20T09:25:00'), createdAt: new Date('2024-11-20T09:15:00') },
    { id: 'MSG020', conversationId: 'CONV002', senderId: 'NUR001', content: 'Welcome home Jean. I am glad you reached out. First things first — how are you feeling? Any severe pain, fever, or unusual redness around the incision site?', readAt: read('2024-11-20T09:40:00'), createdAt: new Date('2024-11-20T09:30:00') },
    { id: 'MSG021', conversationId: 'CONV002', senderId: 'PAT002', content: 'The pain is moderate, around a 4 out of 10. No fever. The incision area looks a bit red but I am not sure if that is normal. There is no pus or drainage.', readAt: read('2024-11-20T09:55:00'), createdAt: new Date('2024-11-20T09:45:00') },
    { id: 'MSG022', conversationId: 'CONV002', senderId: 'NUR001', content: 'Some redness around the incision is completely normal in the first 48 hours — that is part of the healing process. Watch for increasing redness spreading outward, warmth, swelling, or any yellow-green discharge. Those would be signs of infection.', readAt: read('2024-11-20T10:20:00'), createdAt: new Date('2024-11-20T10:00:00') },
    { id: 'MSG023', conversationId: 'CONV002', senderId: 'PAT002', content: 'Okay good, that is reassuring. When should I change the dressing for the first time? And should I use any antiseptic?', readAt: read('2024-11-20T10:45:00'), createdAt: new Date('2024-11-20T10:30:00') },
    { id: 'MSG024', conversationId: 'CONV002', senderId: 'NUR001', content: 'Keep the original dressing on for 48 hours post-surgery, so until tomorrow morning. When you change it, gently clean around the wound with sterile saline or clean water. Pat dry with a clean gauze pad. Apply a fresh sterile adhesive dressing. No antiseptic is needed — it can actually irritate healing tissue.', readAt: read('2024-11-20T11:10:00'), createdAt: new Date('2024-11-20T10:50:00') },
    { id: 'MSG025', conversationId: 'CONV002', senderId: 'PAT002', content: 'Got it. What about showering? I am afraid of getting the wound wet.', readAt: read('2024-11-20T13:20:00'), createdAt: new Date('2024-11-20T13:05:00') },
    { id: 'MSG026', conversationId: 'CONV002', senderId: 'NUR001', content: 'You can take a brief shower after the first dressing change tomorrow. Let water run over the wound gently but do not scrub or soak it. No baths, swimming, or hot tubs for at least two weeks. After showering, pat the area dry and apply a fresh dressing.', readAt: read('2024-11-20T13:45:00'), createdAt: new Date('2024-11-20T13:30:00') },
    { id: 'MSG027', conversationId: 'CONV002', senderId: 'PAT002', content: 'Understood. Now regarding medication — I was prescribed Tramadol 50mg for pain and Augmentin 625mg antibiotic. The Tramadol says take every 6 hours as needed. Can I take it with food?', readAt: read('2024-11-20T16:30:00'), createdAt: new Date('2024-11-20T16:10:00') },
    { id: 'MSG028', conversationId: 'CONV002', senderId: 'NUR001', content: 'Yes, always take Tramadol with food to reduce nausea. Take the Augmentin at regular intervals — one tablet every 8 hours with a meal. Complete the full 7-day course even if you feel better. Do not skip doses as that can lead to antibiotic resistance.', readAt: read('2024-11-20T17:00:00'), createdAt: new Date('2024-11-20T16:40:00') },
    { id: 'MSG029', conversationId: 'CONV002', senderId: 'PAT002', content: 'I set alarms on my phone for the antibiotic. One more question — when can I start walking around and returning to normal activities?', readAt: read('2024-11-21T07:40:00'), createdAt: new Date('2024-11-21T07:20:00') },
    { id: 'MSG030', conversationId: 'CONV002', senderId: 'NUR001', content: 'Short walks around the house are actually encouraged starting today — they help prevent blood clots and promote healing. Avoid heavy lifting over 5 kg for at least 4 weeks. You can return to desk work in about a week, but physical labor should wait 4 to 6 weeks. Listen to your body.', readAt: read('2024-11-21T08:10:00'), createdAt: new Date('2024-11-21T07:50:00') },
    { id: 'MSG031', conversationId: 'CONV002', senderId: 'PAT002', content: 'That is helpful. I work in an office so one week recovery sounds manageable. Should I schedule a follow-up visit for stitch removal?', readAt: read('2024-11-21T10:20:00'), createdAt: new Date('2024-11-21T10:00:00') },
    { id: 'MSG032', conversationId: 'CONV002', senderId: 'NUR001', content: 'If you have dissolvable stitches, they will dissolve on their own within 7 to 14 days. If you have non-dissolvable sutures or staples, you will need to come in around day 10 for removal. Check your discharge papers — it should specify which type was used.', readAt: read('2024-11-21T10:45:00'), createdAt: new Date('2024-11-21T10:25:00') },
    { id: 'MSG033', conversationId: 'CONV002', senderId: 'PAT002', content: 'Just checked — it says absorbable sutures. So I should not need to come back for that. What warning signs should make me go to the emergency room?', readAt: read('2024-11-21T14:10:00'), createdAt: new Date('2024-11-21T13:50:00') },
    { id: 'MSG034', conversationId: 'CONV002', senderId: 'NUR001', content: 'Go to the ER immediately if you experience: fever above 38.5 degrees Celsius, severe or worsening abdominal pain, persistent vomiting, wound opening or heavy drainage, inability to pass gas or stool for more than 3 days, or any signs of difficulty breathing.', readAt: read('2024-11-21T14:35:00'), createdAt: new Date('2024-11-21T14:15:00') },
    { id: 'MSG035', conversationId: 'CONV002', senderId: 'PAT002', content: 'I have noted all of that down. Thank you so much for the thorough guidance. It really helps to have someone to ask these questions.', readAt: read('2024-11-21T16:20:00'), createdAt: new Date('2024-11-21T16:00:00') },
    { id: 'MSG036', conversationId: 'CONV002', senderId: 'NUR001', content: 'You are very welcome Jean. Recovery from an appendectomy is usually smooth. Feel free to message me anytime if you have concerns. I would recommend checking in with us in about a week so we can see how you are healing.', readAt: null, createdAt: new Date('2024-11-21T16:20:00') },
    { id: 'MSG037', conversationId: 'CONV002', senderId: 'PAT002', content: 'Will do. Thanks again and have a good evening!', readAt: null, createdAt: new Date('2024-11-21T16:35:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV003 — PAT003 ↔ NAN001: Childcare scheduling (Nov 25, 1 day)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG038', conversationId: 'CONV003', senderId: 'PAT003', content: 'Hi there! I need to arrange childcare for my daughter Amira next week. She is 4 years old. Are you available Monday through Wednesday?', readAt: read('2024-11-25T07:50:00'), createdAt: new Date('2024-11-25T07:35:00') },
    { id: 'MSG039', conversationId: 'CONV003', senderId: 'NAN001', content: 'Good morning Aisha! Yes, I am available Monday through Wednesday next week. What times would you need coverage? And is there anything specific I should know about Amira beforehand?', readAt: read('2024-11-25T08:10:00'), createdAt: new Date('2024-11-25T07:55:00') },
    { id: 'MSG040', conversationId: 'CONV003', senderId: 'PAT003', content: 'I have medical appointments each day from 9 AM to about 1 PM, so I would need you from 8:30 AM to 1:30 PM. The most important thing to know is that Amira has a severe peanut allergy. She carries an EpiPen.', readAt: read('2024-11-25T08:25:00'), createdAt: new Date('2024-11-25T08:15:00') },
    { id: 'MSG041', conversationId: 'CONV003', senderId: 'NAN001', content: 'That is very important information. I am trained in EpiPen administration and pediatric first aid. Can you show me where the EpiPen is kept and walk me through any other allergy protocols? Are there other food allergies I should be aware of?', readAt: read('2024-11-25T08:45:00'), createdAt: new Date('2024-11-25T08:30:00') },
    { id: 'MSG042', conversationId: 'CONV003', senderId: 'PAT003', content: 'That is reassuring to hear! The EpiPen is in the kitchen drawer by the fridge, and there is a backup in her backpack. No other food allergies, but she is slightly lactose sensitive — she can have small amounts of cheese but no plain milk. She drinks oat milk instead.', readAt: read('2024-11-25T09:10:00'), createdAt: new Date('2024-11-25T08:50:00') },
    { id: 'MSG043', conversationId: 'CONV003', senderId: 'NAN001', content: 'Noted. I will make sure to only offer safe foods. What does her typical morning routine look like? Does she have breakfast before I arrive or should I prepare it?', readAt: read('2024-11-25T09:30:00'), createdAt: new Date('2024-11-25T09:15:00') },
    { id: 'MSG044', conversationId: 'CONV003', senderId: 'PAT003', content: 'She usually has breakfast around 8 AM so she will have eaten already. For a mid-morning snack around 10:30, she likes apple slices with sunflower butter or rice crackers. I will have everything prepared in the fridge with labels.', readAt: read('2024-11-25T09:55:00'), createdAt: new Date('2024-11-25T09:40:00') },
    { id: 'MSG045', conversationId: 'CONV003', senderId: 'NAN001', content: 'Perfect. Labelled snacks make everything easier. Does Amira still nap during the day? And what activities does she enjoy? I like to plan some structured play time.', readAt: read('2024-11-25T10:15:00'), createdAt: new Date('2024-11-25T10:00:00') },
    { id: 'MSG046', conversationId: 'CONV003', senderId: 'PAT003', content: 'She dropped her nap a few months ago but sometimes has quiet time with books around noon. She loves drawing, building with blocks, and playing pretend. She also enjoys being read to — her current favourite is anything about animals.', readAt: read('2024-11-25T10:40:00'), createdAt: new Date('2024-11-25T10:20:00') },
    { id: 'MSG047', conversationId: 'CONV003', senderId: 'NAN001', content: 'That sounds lovely. I will bring some animal stickers and a colouring book. Is she allowed screen time or do you prefer screen-free activities?', readAt: read('2024-11-25T11:00:00'), createdAt: new Date('2024-11-25T10:45:00') },
    { id: 'MSG048', conversationId: 'CONV003', senderId: 'PAT003', content: 'We try to limit screens to 30 minutes maximum if needed. I would prefer she does not have any, but if she gets really fussy a short episode of Bluey is fine. The tablet is on the shelf in the living room with her profile set up.', readAt: read('2024-11-25T12:10:00'), createdAt: new Date('2024-11-25T11:50:00') },
    { id: 'MSG049', conversationId: 'CONV003', senderId: 'NAN001', content: 'Understood — screens only as a last resort. One more thing: does she have any behavioural triggers or comfort items I should know about? Some children can be anxious when a parent leaves.', readAt: read('2024-11-25T12:30:00'), createdAt: new Date('2024-11-25T12:15:00') },
    { id: 'MSG050', conversationId: 'CONV003', senderId: 'PAT003', content: 'She does get a little teary at drop-off moments but she settles quickly once distracted. Her stuffed bunny, Mr. Floppy, is her comfort toy — if she is upset, giving her that usually calms her right down. She is generally a happy child once she warms up.', readAt: read('2024-11-25T13:00:00'), createdAt: new Date('2024-11-25T12:40:00') },
    { id: 'MSG051', conversationId: 'CONV003', senderId: 'NAN001', content: 'Mr. Floppy — got it! I will make sure to have him nearby. I will plan to arrive at 8:20 AM on Monday to give us a few minutes for a handoff before you leave. Does that work?', readAt: read('2024-11-25T13:20:00'), createdAt: new Date('2024-11-25T13:05:00') },
    { id: 'MSG052', conversationId: 'CONV003', senderId: 'PAT003', content: 'That is perfect. I will text you my address and the gate code. Also, my neighbour Mrs. Ramgoolam next door has a spare key and knows you will be coming, just in case of any emergency.', readAt: read('2024-11-25T14:50:00'), createdAt: new Date('2024-11-25T14:30:00') },
    { id: 'MSG053', conversationId: 'CONV003', senderId: 'NAN001', content: 'Great, having a backup contact nearby is always wise. I will confirm everything on Sunday evening. Looking forward to meeting Amira — she sounds like a wonderful little girl!', readAt: read('2024-11-25T15:10:00'), createdAt: new Date('2024-11-25T14:55:00') },
    { id: 'MSG054', conversationId: 'CONV003', senderId: 'PAT003', content: 'She really is. Thank you so much for being thorough with all the questions. It gives me a lot of confidence leaving her with you. See you Monday!', readAt: null, createdAt: new Date('2024-11-25T15:15:00') },
    { id: 'MSG055', conversationId: 'CONV003', senderId: 'NAN001', content: 'My pleasure Aisha. Have a lovely weekend and see you bright and early Monday morning!', readAt: null, createdAt: new Date('2024-11-25T15:25:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV004 — PAT001 ↔ PHARM001: Prescription refill & drug interaction (Dec 1, 1 day)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG056', conversationId: 'CONV004', senderId: 'PAT001', content: 'Good morning. I need to refill my Metformin 500mg prescription. My prescription number is PRE001. I also had a question about a new supplement I want to start taking.', readAt: read('2024-12-01T10:20:00'), createdAt: new Date('2024-12-01T10:05:00') },
    { id: 'MSG057', conversationId: 'CONV004', senderId: 'PHARM001', content: 'Good morning Emma. I can see your Metformin prescription in the system — it is eligible for refill. I will prepare a 30-day supply. What supplement are you considering?', readAt: read('2024-12-01T10:35:00'), createdAt: new Date('2024-12-01T10:25:00') },
    { id: 'MSG058', conversationId: 'CONV004', senderId: 'PAT001', content: 'I was reading about berberine supplements for blood sugar support. A friend recommended it. Is it safe to take alongside Metformin?', readAt: read('2024-12-01T10:55:00'), createdAt: new Date('2024-12-01T10:40:00') },
    { id: 'MSG059', conversationId: 'CONV004', senderId: 'PHARM001', content: 'That is an important question. Berberine actually works through a similar mechanism as Metformin — both activate the AMPK pathway. Taking them together could potentially cause your blood sugar to drop too low, leading to hypoglycemia. I would strongly recommend discussing this with Dr. Johnson before starting it.', readAt: read('2024-12-01T11:15:00'), createdAt: new Date('2024-12-01T11:00:00') },
    { id: 'MSG060', conversationId: 'CONV004', senderId: 'PAT001', content: 'Oh I had no idea they worked the same way. I will definitely check with my doctor first. Thank you for catching that. By the way, is there a generic version of my Lisinopril that might be more affordable?', readAt: read('2024-12-01T11:35:00'), createdAt: new Date('2024-12-01T11:20:00') },
    { id: 'MSG061', conversationId: 'CONV004', senderId: 'PHARM001', content: 'Lisinopril is already a generic medication, so you are getting the most affordable option. However, I can check if we have it from a different manufacturer that might be priced lower. Let me look into that for you.', readAt: read('2024-12-01T11:55:00'), createdAt: new Date('2024-12-01T11:40:00') },
    { id: 'MSG062', conversationId: 'CONV004', senderId: 'PHARM001', content: 'I checked our inventory and we do have Lisinopril 10mg from a different supplier at about 15% less. The active ingredient and dosage are identical. Would you like me to switch to that for your next refill?', readAt: read('2024-12-01T12:20:00'), createdAt: new Date('2024-12-01T12:05:00') },
    { id: 'MSG063', conversationId: 'CONV004', senderId: 'PAT001', content: 'Yes please, every bit helps! When will my Metformin be ready for pickup?', readAt: read('2024-12-01T12:40:00'), createdAt: new Date('2024-12-01T12:25:00') },
    { id: 'MSG064', conversationId: 'CONV004', senderId: 'PHARM001', content: 'Your Metformin 500mg refill will be ready by 2 PM today. I have also noted the Lisinopril manufacturer switch for your next refill in January. Is there anything else you need?', readAt: read('2024-12-01T13:00:00'), createdAt: new Date('2024-12-01T12:45:00') },
    { id: 'MSG065', conversationId: 'CONV004', senderId: 'PAT001', content: 'Actually, yes. I sometimes forget whether I have taken my evening dose. Is there a pill organizer you would recommend? Also, does it matter if I take Metformin before or after meals?', readAt: read('2024-12-01T14:15:00'), createdAt: new Date('2024-12-01T14:00:00') },
    { id: 'MSG066', conversationId: 'CONV004', senderId: 'PHARM001', content: 'We carry weekly pill organizers with AM and PM compartments — I will set one aside for you with your refill. As for timing, Metformin should always be taken with food, ideally at the start of a meal. This reduces the gastrointestinal side effects like nausea and improves absorption.', readAt: read('2024-12-01T14:40:00'), createdAt: new Date('2024-12-01T14:20:00') },
    { id: 'MSG067', conversationId: 'CONV004', senderId: 'PAT001', content: 'That explains the stomach upset I had last week — I took it on an empty stomach. I will be more careful about that. How much is the pill organizer?', readAt: read('2024-12-01T15:00:00'), createdAt: new Date('2024-12-01T14:45:00') },
    { id: 'MSG068', conversationId: 'CONV004', senderId: 'PHARM001', content: 'The organizer is Rs 250. I will add it to your order. Also, a helpful tip: if you do miss a dose and it is close to your next scheduled dose, just skip the missed one. Never double up on Metformin as it can cause lactic acidosis in rare cases.', readAt: read('2024-12-01T15:20:00'), createdAt: new Date('2024-12-01T15:05:00') },
    { id: 'MSG069', conversationId: 'CONV004', senderId: 'PAT001', content: 'That is very good to know. I have done that once or twice before. I will be more careful going forward. Is it okay to pick up around 3 PM?', readAt: read('2024-12-01T16:00:00'), createdAt: new Date('2024-12-01T15:40:00') },
    { id: 'MSG070', conversationId: 'CONV004', senderId: 'PHARM001', content: 'Absolutely. Everything will be ready and waiting. I have prepared your Metformin 500mg (60 tablets), the AM/PM pill organizer, and I have flagged the berberine interaction note on your profile. See you at 3 PM!', readAt: read('2024-12-01T16:20:00'), createdAt: new Date('2024-12-01T16:00:00') },
    { id: 'MSG071', conversationId: 'CONV004', senderId: 'PAT001', content: 'Wonderful, thank you for being so thorough. See you soon!', readAt: null, createdAt: new Date('2024-12-01T16:10:00') },
    { id: 'MSG072', conversationId: 'CONV004', senderId: 'PHARM001', content: 'You are welcome Emma. Always happy to help. Take care!', readAt: null, createdAt: new Date('2024-12-01T16:15:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV005 — DOC002 ↔ NUR002: Coordinating care for PAT004 (Dec 3–4, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG073', conversationId: 'CONV005', senderId: 'DOC002', content: 'Good morning. I wanted to check in on Mr. Doorgakant in Room 4B. I reviewed his overnight vitals and noticed his blood pressure has been trending upward — 148/92 at midnight, 152/95 at 4 AM. What is the latest reading?', readAt: read('2024-12-03T07:20:00'), createdAt: new Date('2024-12-03T07:10:00') },
    { id: 'MSG074', conversationId: 'CONV005', senderId: 'NUR002', content: 'Good morning Dr. Patel. I just took his 7 AM vitals: BP is 155/96, heart rate 88 bpm, temperature 37.1 C, SpO2 97%. He is also complaining of a mild headache this morning which he did not have yesterday.', readAt: read('2024-12-03T07:35:00'), createdAt: new Date('2024-12-03T07:25:00') },
    { id: 'MSG075', conversationId: 'CONV005', senderId: 'DOC002', content: 'The upward trend with a new headache is concerning. Is he still on Amlodipine 5mg once daily? I think we need to increase to 10mg. Also, please check if he has been compliant with the low-sodium diet.', readAt: read('2024-12-03T07:55:00'), createdAt: new Date('2024-12-03T07:40:00') },
    { id: 'MSG076', conversationId: 'CONV005', senderId: 'NUR002', content: 'Yes, he is on Amlodipine 5mg daily and Atorvastatin 40mg nightly. Regarding diet compliance — I noticed his family brought in outside food last evening. It appeared to be fried noodles and salted fish. I did note it in the chart.', readAt: read('2024-12-03T08:15:00'), createdAt: new Date('2024-12-03T08:00:00') },
    { id: 'MSG077', conversationId: 'CONV005', senderId: 'DOC002', content: 'That explains a lot. High sodium intake will counteract the antihypertensives. Please speak with the family about dietary restrictions — they need to understand that outside food with high salt content is undermining his treatment. I will place the order to increase Amlodipine to 10mg starting tonight.', readAt: read('2024-12-03T08:35:00'), createdAt: new Date('2024-12-03T08:20:00') },
    { id: 'MSG078', conversationId: 'CONV005', senderId: 'NUR002', content: 'Understood. I will have a conversation with the family during visiting hours at noon. Should I also schedule a dietary consult with the hospital nutritionist?', readAt: read('2024-12-03T08:55:00'), createdAt: new Date('2024-12-03T08:40:00') },
    { id: 'MSG079', conversationId: 'CONV005', senderId: 'DOC002', content: 'Yes, please arrange that. Also, let us increase his BP monitoring to every 4 hours instead of every 8. If systolic exceeds 160 or diastolic exceeds 100, please contact me immediately. We may need to add a second antihypertensive.', readAt: read('2024-12-03T09:10:00'), createdAt: new Date('2024-12-03T08:55:00') },
    { id: 'MSG080', conversationId: 'CONV005', senderId: 'NUR002', content: 'Noted. BP monitoring increased to q4h and I have set the alert thresholds. The dietary consult is requested for tomorrow morning. How are his latest lipid panel results looking?', readAt: read('2024-12-03T12:20:00'), createdAt: new Date('2024-12-03T12:00:00') },
    { id: 'MSG081', conversationId: 'CONV005', senderId: 'DOC002', content: 'His total cholesterol is still at 245 mg/dL and LDL is 162 mg/dL despite two months on Atorvastatin. I am considering switching to Rosuvastatin 20mg as it may be more effective for him. His liver function tests are normal so the switch should be safe.', readAt: read('2024-12-03T12:45:00'), createdAt: new Date('2024-12-03T12:30:00') },
    { id: 'MSG082', conversationId: 'CONV005', senderId: 'NUR002', content: 'I spoke with the family at noon. They were apologetic and said they did not realize how much salt was in the food. I gave them the dietary guidelines sheet and explained what is allowed. They agreed to only bring fresh fruits going forward.', readAt: read('2024-12-03T15:00:00'), createdAt: new Date('2024-12-03T14:40:00') },
    { id: 'MSG083', conversationId: 'CONV005', senderId: 'DOC002', content: 'Good work. How was his noon BP reading after the increased monitoring?', readAt: read('2024-12-03T15:20:00'), createdAt: new Date('2024-12-03T15:05:00') },
    { id: 'MSG084', conversationId: 'CONV005', senderId: 'NUR002', content: 'Noon reading was 150/94 — still elevated but not worse. He says the headache improved after paracetamol. His 4 PM reading is coming up shortly, I will report it.', readAt: read('2024-12-03T16:30:00'), createdAt: new Date('2024-12-03T15:15:00') },
    { id: 'MSG085', conversationId: 'CONV005', senderId: 'NUR002', content: '4 PM update: BP 146/91, heart rate 82 bpm. Slight improvement. Headache has resolved. He ate the hospital lunch (grilled chicken, steamed vegetables, brown rice) without complaint.', readAt: read('2024-12-03T16:45:00'), createdAt: new Date('2024-12-03T16:15:00') },
    { id: 'MSG086', conversationId: 'CONV005', senderId: 'DOC002', content: 'Good, the trend is moving in the right direction. Let us see the effect of the Amlodipine dose increase overnight. Continue q4h monitoring. I have also placed the order to switch from Atorvastatin to Rosuvastatin 20mg starting tomorrow evening.', readAt: read('2024-12-03T17:10:00'), createdAt: new Date('2024-12-03T16:50:00') },
    { id: 'MSG087', conversationId: 'CONV005', senderId: 'NUR002', content: 'Morning update Dr. Patel. Overnight readings are encouraging: midnight 140/88, 4 AM 138/86, 7 AM 136/84. Headache has not returned. He slept well and reported feeling better this morning.', readAt: read('2024-12-04T07:30:00'), createdAt: new Date('2024-12-04T07:15:00') },
    { id: 'MSG088', conversationId: 'CONV005', senderId: 'DOC002', content: 'Excellent improvement. The higher Amlodipine dose combined with the dietary compliance is clearly working. Let us keep monitoring q4h through today and if readings stay below 140/90, we can discuss discharge planning for Friday.', readAt: read('2024-12-04T08:00:00'), createdAt: new Date('2024-12-04T07:40:00') },
    { id: 'MSG089', conversationId: 'CONV005', senderId: 'NUR002', content: 'Sounds like a plan. The nutritionist is seeing him at 10 AM today to create a home meal plan. I will also start preparing the discharge medication list and patient education materials.', readAt: read('2024-12-04T08:20:00'), createdAt: new Date('2024-12-04T08:05:00') },
    { id: 'MSG090', conversationId: 'CONV005', senderId: 'DOC002', content: 'Perfect. Make sure the discharge plan includes: Amlodipine 10mg once daily, Rosuvastatin 20mg nightly, low-sodium diet, daily home BP monitoring, and a follow-up appointment in two weeks. Great teamwork on this one.', readAt: null, createdAt: new Date('2024-12-04T08:25:00') },
    { id: 'MSG091', conversationId: 'CONV005', senderId: 'NUR002', content: 'All noted. I will have the discharge summary drafted by this afternoon for your review. Thank you Dr. Patel.', readAt: null, createdAt: new Date('2024-12-04T08:35:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV006 — PAT005 ↔ DOC003: Cardiology follow-up (Dec 8–10, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG092', conversationId: 'CONV006', senderId: 'PAT005', content: 'Good morning Dr. Dupont. I received a notification that my echocardiogram results are ready. I have been quite anxious about them. Could you give me an overview before our next appointment?', readAt: read('2024-12-08T09:20:00'), createdAt: new Date('2024-12-08T09:10:00') },
    { id: 'MSG093', conversationId: 'CONV006', senderId: 'DOC003', content: 'Good morning Nadia. I understand your anxiety and I have good news overall. Your echocardiogram shows your left ventricular ejection fraction is at 55%, which is within the normal range of 55-70%. This is an improvement from the 50% we measured six months ago.', readAt: read('2024-12-08T09:45:00'), createdAt: new Date('2024-12-08T09:30:00') },
    { id: 'MSG094', conversationId: 'CONV006', senderId: 'PAT005', content: 'Oh that is such a relief! I was worried it might have gotten worse. What about the mild valve regurgitation you mentioned last time?', readAt: read('2024-12-08T10:05:00'), createdAt: new Date('2024-12-08T09:50:00') },
    { id: 'MSG095', conversationId: 'CONV006', senderId: 'DOC003', content: 'The mild mitral valve regurgitation is stable — it has not progressed. This is what we call trace to mild, which is very common and usually does not require treatment. We will continue to monitor it with annual echocardiograms.', readAt: read('2024-12-08T10:25:00'), createdAt: new Date('2024-12-08T10:10:00') },
    { id: 'MSG096', conversationId: 'CONV006', senderId: 'PAT005', content: 'That is reassuring. I have been taking the Bisoprolol 5mg as prescribed and trying to exercise regularly. I walk for 30 minutes most days. Should I be doing more?', readAt: read('2024-12-08T14:20:00'), createdAt: new Date('2024-12-08T14:00:00') },
    { id: 'MSG097', conversationId: 'CONV006', senderId: 'DOC003', content: 'Walking 30 minutes daily is excellent for your heart health. You can gradually increase the pace or duration if you feel comfortable, but avoid sudden intense exercise. The Bisoprolol is doing its job of keeping your heart rate controlled. What has your resting heart rate been?', readAt: read('2024-12-08T14:40:00'), createdAt: new Date('2024-12-08T14:25:00') },
    { id: 'MSG098', conversationId: 'CONV006', senderId: 'PAT005', content: 'My resting heart rate has been between 62 and 68 bpm when I check in the mornings. Sometimes it goes up to about 75 after climbing stairs. I have also noticed occasional palpitations at night — maybe once or twice a week. Should I be worried?', readAt: read('2024-12-09T08:30:00'), createdAt: new Date('2024-12-09T08:10:00') },
    { id: 'MSG099', conversationId: 'CONV006', senderId: 'DOC003', content: 'Your resting heart rate is well controlled on the Bisoprolol. The occasional palpitations could be benign premature beats, which are common and usually harmless. However, I would like to capture them on a recording. I am going to order a 48-hour Holter monitor for you — you will wear it and it records every heartbeat.', readAt: read('2024-12-09T09:00:00'), createdAt: new Date('2024-12-09T08:40:00') },
    { id: 'MSG100', conversationId: 'CONV006', senderId: 'PAT005', content: 'I have heard of those. Is it uncomfortable to wear? And can I still go about my daily activities while wearing it?', readAt: read('2024-12-09T09:30:00'), createdAt: new Date('2024-12-09T09:10:00') },
    { id: 'MSG101', conversationId: 'CONV006', senderId: 'DOC003', content: 'It is a small device about the size of a mobile phone that clips to your waistband. Small adhesive electrodes are placed on your chest. You can do all your normal activities — in fact, that is the point, to record what happens during your regular day. Just avoid getting the electrodes wet, so no showers with it on.', readAt: read('2024-12-09T10:00:00'), createdAt: new Date('2024-12-09T09:40:00') },
    { id: 'MSG102', conversationId: 'CONV006', senderId: 'PAT005', content: 'That sounds manageable. When should I come in for that? Also, I wanted to ask about my blood thinners. My gums have been bleeding a bit more when brushing. Is that a side effect?', readAt: read('2024-12-09T14:30:00'), createdAt: new Date('2024-12-09T14:10:00') },
    { id: 'MSG103', conversationId: 'CONV006', senderId: 'DOC003', content: 'Yes, increased bleeding tendency is a known side effect of Warfarin. Gum bleeding during brushing is relatively common. Use a soft-bristled toothbrush and be gentle. However, if you notice bleeding that does not stop, blood in your urine or stool, or unusual bruising, contact me immediately. When was your last INR test?', readAt: read('2024-12-09T15:00:00'), createdAt: new Date('2024-12-09T14:40:00') },
    { id: 'MSG104', conversationId: 'CONV006', senderId: 'PAT005', content: 'My last INR was about three weeks ago — it was 2.4. I am due for another one soon. The gum bleeding is mild and stops on its own, so I think it is manageable. I switched to a softer toothbrush last week and it helped.', readAt: read('2024-12-10T09:10:00'), createdAt: new Date('2024-12-10T08:50:00') },
    { id: 'MSG105', conversationId: 'CONV006', senderId: 'DOC003', content: 'An INR of 2.4 is right in our target range of 2.0 to 3.0. Let us get your INR rechecked when you come in for the Holter monitor fitting. I have availability next Tuesday, December 17th at 10 AM. Would that work for you?', readAt: read('2024-12-10T09:35:00'), createdAt: new Date('2024-12-10T09:15:00') },
    { id: 'MSG106', conversationId: 'CONV006', senderId: 'PAT005', content: 'Tuesday at 10 AM works perfectly. So to summarize, I will come in for the Holter monitor fitting and an INR blood draw. Is there anything I should do to prepare beforehand?', readAt: read('2024-12-10T10:00:00'), createdAt: new Date('2024-12-10T09:40:00') },
    { id: 'MSG107', conversationId: 'CONV006', senderId: 'DOC003', content: 'No special preparation needed for either test. Take your medications as normal that morning including the Bisoprolol and Warfarin. Wear a loose-fitting top that makes it easy to place the electrodes. The INR is just a quick finger prick. Plan for about 30 minutes total.', readAt: read('2024-12-10T10:25:00'), createdAt: new Date('2024-12-10T10:05:00') },
    { id: 'MSG108', conversationId: 'CONV006', senderId: 'PAT005', content: 'Perfect. One last question — my sister was recently diagnosed with atrial fibrillation. Is there a genetic component I should be concerned about?', readAt: read('2024-12-10T14:20:00'), createdAt: new Date('2024-12-10T14:00:00') },
    { id: 'MSG109', conversationId: 'CONV006', senderId: 'DOC003', content: 'There can be a genetic predisposition to atrial fibrillation, especially if a first-degree relative is affected. This is actually another reason the Holter monitor is a good idea — it will help us detect any irregular rhythms, including intermittent AF. Your current medications and lifestyle changes are protective factors.', readAt: read('2024-12-10T14:50:00'), createdAt: new Date('2024-12-10T14:30:00') },
    { id: 'MSG110', conversationId: 'CONV006', senderId: 'PAT005', content: 'Thank you for explaining everything so clearly Dr. Dupont. I feel much more at ease now. I will see you Tuesday the 17th at 10 AM.', readAt: null, createdAt: new Date('2024-12-10T15:00:00') },
    { id: 'MSG111', conversationId: 'CONV006', senderId: 'DOC003', content: 'You are welcome Nadia. The results are genuinely encouraging and you should feel good about the progress. Keep up the walking and take your medications consistently. See you on the 17th. Do not hesitate to message if the palpitations become more frequent or severe before then.', readAt: null, createdAt: new Date('2024-12-10T15:15:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV007 — PAT001 ↔ LAB001: Lab test results discussion (Dec 12–13, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG112', conversationId: 'CONV007', senderId: 'PAT001', content: 'Hello, I had blood work done at your lab on Monday — requisition number LR-2024-0487. My doctor mentioned the results should be available by now. Could you help me understand them?', readAt: read('2024-12-12T08:25:00'), createdAt: new Date('2024-12-12T08:10:00') },
    { id: 'MSG113', conversationId: 'CONV007', senderId: 'LAB001', content: 'Good morning Emma. Yes, I can see your results have been processed and released to your doctor. I can walk you through the key findings. Your complete blood count looks normal across the board — haemoglobin is 13.2 g/dL, white blood cells 6,800, and platelets 245,000. All within reference ranges.', readAt: read('2024-12-12T08:45:00'), createdAt: new Date('2024-12-12T08:30:00') },
    { id: 'MSG114', conversationId: 'CONV007', senderId: 'PAT001', content: 'That is good to hear. What about the metabolic panel? I am particularly concerned about my fasting glucose and cholesterol. I have been working on improving my diet lately.', readAt: read('2024-12-12T09:05:00'), createdAt: new Date('2024-12-12T08:50:00') },
    { id: 'MSG115', conversationId: 'CONV007', senderId: 'LAB001', content: 'Your fasting glucose came back at 132 mg/dL. The normal range is 70 to 100 mg/dL, so it is elevated but lower than your previous result of 156 mg/dL from September. Your HbA1c is 6.9%, which is also an improvement from the 7.2% we measured last time. The dietary changes seem to be having a positive effect.', readAt: read('2024-12-12T09:30:00'), createdAt: new Date('2024-12-12T09:10:00') },
    { id: 'MSG116', conversationId: 'CONV007', senderId: 'PAT001', content: 'Oh that is wonderful! I have been following Dr. Johnson\'s advice about brown rice and walking daily. What about the lipid panel? My cholesterol has been a worry for me.', readAt: read('2024-12-12T09:50:00'), createdAt: new Date('2024-12-12T09:35:00') },
    { id: 'MSG117', conversationId: 'CONV007', senderId: 'LAB001', content: 'Your lipid panel results are mixed. Total cholesterol is 218 mg/dL, which is borderline high — the desirable level is below 200. LDL cholesterol is 138 mg/dL, still above the optimal range of below 100. However, your HDL cholesterol is 52 mg/dL, which is good. Triglycerides are at 140 mg/dL, within the normal range of below 150.', readAt: read('2024-12-12T10:15:00'), createdAt: new Date('2024-12-12T09:55:00') },
    { id: 'MSG118', conversationId: 'CONV007', senderId: 'PAT001', content: 'So the LDL is still too high. Is that the "bad" cholesterol? What does that number actually mean in terms of health risk?', readAt: read('2024-12-12T10:40:00'), createdAt: new Date('2024-12-12T10:20:00') },
    { id: 'MSG119', conversationId: 'CONV007', senderId: 'LAB001', content: 'Correct, LDL is often referred to as bad cholesterol because elevated levels contribute to plaque buildup in your arteries. At 138, you are in the borderline high category. Combined with your diabetes, your doctor may want to discuss lipid-lowering strategies. The good news is your HDL, the protective cholesterol, is at a healthy level. Exercise tends to raise HDL, so your walking is helping there.', readAt: read('2024-12-12T11:00:00'), createdAt: new Date('2024-12-12T10:45:00') },
    { id: 'MSG120', conversationId: 'CONV007', senderId: 'PAT001', content: 'That makes sense. Were there any other values that were flagged? I noticed the lab form also included kidney function tests.', readAt: read('2024-12-12T14:20:00'), createdAt: new Date('2024-12-12T14:00:00') },
    { id: 'MSG121', conversationId: 'CONV007', senderId: 'LAB001', content: 'Your kidney function is reassuring. Creatinine is 0.9 mg/dL, which is normal. Your estimated GFR is 92 mL/min, well above the threshold of 60 that we monitor closely in diabetic patients. Blood urea nitrogen is 16 mg/dL, also normal. Your kidneys are functioning well.', readAt: read('2024-12-12T14:45:00'), createdAt: new Date('2024-12-12T14:25:00') },
    { id: 'MSG122', conversationId: 'CONV007', senderId: 'PAT001', content: 'That is a relief. My doctor had mentioned that diabetes can affect the kidneys over time so I was anxious about that. What about the liver function tests? I take Metformin and Lisinopril daily.', readAt: read('2024-12-12T15:10:00'), createdAt: new Date('2024-12-12T14:50:00') },
    { id: 'MSG123', conversationId: 'CONV007', senderId: 'LAB001', content: 'Liver enzymes are all within normal limits. ALT is 24 U/L and AST is 22 U/L — both well within the reference range of 7 to 56 U/L. This is important because Metformin is processed by the liver. No concerns there at all.', readAt: read('2024-12-12T15:35:00'), createdAt: new Date('2024-12-12T15:15:00') },
    { id: 'MSG124', conversationId: 'CONV007', senderId: 'PAT001', content: 'Thank you for being so thorough. One last question — how often should I be getting these blood tests done? My doctor mentioned every three months for the HbA1c but I was not sure about the rest.', readAt: read('2024-12-13T08:20:00'), createdAt: new Date('2024-12-13T08:00:00') },
    { id: 'MSG125', conversationId: 'CONV007', senderId: 'LAB001', content: 'For diabetic patients, we typically recommend HbA1c every three months as you mentioned. The full metabolic panel including kidney function should be done every six months. Lipid panels are usually annual unless your doctor is actively managing cholesterol, in which case every six months. Your doctor can adjust the frequency based on your results.', readAt: read('2024-12-13T08:45:00'), createdAt: new Date('2024-12-13T08:25:00') },
    { id: 'MSG126', conversationId: 'CONV007', senderId: 'PAT001', content: 'That is very helpful. I will set reminders in my calendar so I do not miss any tests. Should I fast before every blood draw or only for certain tests?', readAt: read('2024-12-13T09:10:00'), createdAt: new Date('2024-12-13T08:50:00') },
    { id: 'MSG127', conversationId: 'CONV007', senderId: 'LAB001', content: 'Fasting for 8 to 12 hours is required for the lipid panel and fasting glucose. The HbA1c, complete blood count, kidney and liver function tests do not require fasting. When in doubt, fasting is always safe — it never affects results negatively. Just remember to stay hydrated with plain water, as dehydration can make the blood draw more difficult.', readAt: read('2024-12-13T09:35:00'), createdAt: new Date('2024-12-13T09:15:00') },
    { id: 'MSG128', conversationId: 'CONV007', senderId: 'PAT001', content: 'Noted. I always drink water beforehand so that is good. Thank you so much for explaining all of this. It really helps me understand my health better when I know what the numbers mean.', readAt: null, createdAt: new Date('2024-12-13T09:40:00') },
    { id: 'MSG129', conversationId: 'CONV007', senderId: 'LAB001', content: 'You are very welcome Emma. Understanding your results empowers you to make better health decisions. The overall trend is positive — keep up the lifestyle changes. We will see you for your next round of tests in March. Take care!', readAt: null, createdAt: new Date('2024-12-13T09:55:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV008 — PAT002 ↔ EMW001: Emergency follow-up (Dec 14–15, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG130', conversationId: 'CONV008', senderId: 'PAT002', content: 'Hello, I wanted to reach out and thank you personally. You were part of the emergency team that responded when I collapsed at the Caudan Waterfront last Tuesday. I was the gentleman with the severe asthma attack near the food court.', readAt: read('2024-12-14T09:25:00'), createdAt: new Date('2024-12-14T09:10:00') },
    { id: 'MSG131', conversationId: 'CONV008', senderId: 'EMW001', content: 'Jean, of course I remember. I am very glad to hear from you and even more glad you are doing well enough to message. How are you feeling now? Have you been discharged from the hospital?', readAt: read('2024-12-14T09:45:00'), createdAt: new Date('2024-12-14T09:30:00') },
    { id: 'MSG132', conversationId: 'CONV008', senderId: 'PAT002', content: 'Yes, I was discharged on Thursday. I spent two nights in the hospital for observation. The doctors said my oxygen levels dropped to 85% before you arrived. They told me the nebulizer treatment you administered on scene was critical — another few minutes without intervention could have been very serious.', readAt: read('2024-12-14T10:10:00'), createdAt: new Date('2024-12-14T09:50:00') },
    { id: 'MSG133', conversationId: 'CONV008', senderId: 'EMW001', content: 'I am relieved the timing worked out. Our response time was about 6 minutes from dispatch. When we arrived, your SpO2 was indeed at 85% and you were using accessory muscles to breathe. We started with continuous nebulized salbutamol and administered IV hydrocortisone. Do you recall much of what happened?', readAt: read('2024-12-14T10:35:00'), createdAt: new Date('2024-12-14T10:15:00') },
    { id: 'MSG134', conversationId: 'CONV008', senderId: 'PAT002', content: 'Honestly, it is a blur. I remember feeling my chest tighten suddenly and reaching for my inhaler, but it was nearly empty — only one puff came out and it was not enough. The next thing I clearly remember is waking up in the ambulance with the oxygen mask on. My wife said a bystander called 114 while she tried to keep me calm.', readAt: read('2024-12-14T11:00:00'), createdAt: new Date('2024-12-14T10:40:00') },
    { id: 'MSG135', conversationId: 'CONV008', senderId: 'EMW001', content: 'That bystander did exactly the right thing. An important lesson here is to always carry a full rescue inhaler. I would also recommend asking your doctor about an asthma action plan — a written guide that tells you what to do when symptoms escalate, step by step, before it becomes an emergency. Have you discussed this with your pulmonologist?', readAt: read('2024-12-14T11:30:00'), createdAt: new Date('2024-12-14T11:10:00') },
    { id: 'MSG136', conversationId: 'CONV008', senderId: 'PAT002', content: 'I have an appointment with Dr. Ramsaran next week. The hospital doctor mentioned I should be on a daily controller medication, not just the rescue inhaler. I have been managing with salbutamol alone for years. Maybe that is not enough anymore.', readAt: read('2024-12-14T14:20:00'), createdAt: new Date('2024-12-14T14:00:00') },
    { id: 'MSG137', conversationId: 'CONV008', senderId: 'EMW001', content: 'That is a very important conversation to have. Many asthma patients underestimate their condition by relying solely on rescue inhalers. If you are needing your rescue inhaler more than twice a week, that usually indicates your asthma is not well controlled and a daily inhaled corticosteroid should be considered. The pattern we see in severe attacks often involves months of gradually worsening symptoms that go unnoticed.', readAt: read('2024-12-14T14:50:00'), createdAt: new Date('2024-12-14T14:30:00') },
    { id: 'MSG138', conversationId: 'CONV008', senderId: 'PAT002', content: 'Now that you say that, I have been using the rescue inhaler almost daily for the past month, especially in the mornings. I thought it was just the change in weather. What are the warning signs I should watch for going forward?', readAt: read('2024-12-14T15:15:00'), createdAt: new Date('2024-12-14T15:00:00') },
    { id: 'MSG139', conversationId: 'CONV008', senderId: 'EMW001', content: 'Daily use is a red flag. Key warning signs to monitor: waking up at night due to coughing or wheezing, needing your rescue inhaler more than twice a week, shortness of breath during activities that were previously fine, and a peak flow reading below 80% of your personal best. I would strongly recommend getting a peak flow meter — they are inexpensive and can catch decline before it becomes an emergency.', readAt: read('2024-12-14T15:45:00'), createdAt: new Date('2024-12-14T15:20:00') },
    { id: 'MSG140', conversationId: 'CONV008', senderId: 'PAT002', content: 'I have experienced the night coughing as well. I will mention all of this to Dr. Ramsaran. Is there anything specific about my environment at home that could be triggering the attacks? I live near the harbour and the air can be quite humid.', readAt: read('2024-12-15T08:30:00'), createdAt: new Date('2024-12-15T08:10:00') },
    { id: 'MSG141', conversationId: 'CONV008', senderId: 'EMW001', content: 'Humidity itself can be a trigger, and living near the harbour means potential exposure to marine air pollutants. Common indoor triggers include dust mites, mould in damp areas, cockroach allergens, and pet dander. I would suggest checking for mould in your bathroom and kitchen, using allergen-proof covers on your pillows and mattress, and keeping windows closed on high-humidity days.', readAt: read('2024-12-15T09:00:00'), createdAt: new Date('2024-12-15T08:40:00') },
    { id: 'MSG142', conversationId: 'CONV008', senderId: 'PAT002', content: 'We do have some mould in the bathroom ceiling actually. I have been meaning to deal with it. I did not connect it to my breathing issues. I will get that cleaned up properly this weekend. Should I also be concerned about exercise? I used to jog but I stopped because it made me wheeze.', readAt: read('2024-12-15T09:30:00'), createdAt: new Date('2024-12-15T09:10:00') },
    { id: 'MSG143', conversationId: 'CONV008', senderId: 'EMW001', content: 'Exercise-induced bronchoconstriction is common in asthma patients, but exercise should not be avoided entirely — it actually strengthens the respiratory muscles over time. Once your asthma is properly controlled with a daily medication, you should be able to return to jogging. A warm-up period of 10 to 15 minutes before intense exercise helps prevent the airway narrowing. Your doctor may also recommend taking two puffs of salbutamol 15 minutes before exercise as a precaution.', readAt: read('2024-12-15T10:00:00'), createdAt: new Date('2024-12-15T09:35:00') },
    { id: 'MSG144', conversationId: 'CONV008', senderId: 'PAT002', content: 'That is really encouraging. I miss running. I also wanted to ask — should I get a medical alert bracelet? My wife is worried about another episode happening when I am alone.', readAt: read('2024-12-15T14:20:00'), createdAt: new Date('2024-12-15T14:00:00') },
    { id: 'MSG145', conversationId: 'CONV008', senderId: 'EMW001', content: 'A medical alert bracelet is an excellent idea, especially given the severity of your recent attack. It should list "severe asthma" and any medication allergies. From our perspective as emergency responders, having that information immediately visible can save critical minutes in treatment decisions. Also, make sure your wife and close colleagues know where you keep your rescue inhaler and how to use it on your behalf if needed.', readAt: read('2024-12-15T14:50:00'), createdAt: new Date('2024-12-15T14:25:00') },
    { id: 'MSG146', conversationId: 'CONV008', senderId: 'PAT002', content: 'I will order one this week. Thank you so much for all this guidance and again for saving my life last Tuesday. Your team was incredible — professional and reassuring even when I was panicking. I truly cannot thank you enough.', readAt: null, createdAt: new Date('2024-12-15T15:00:00') },
    { id: 'MSG147', conversationId: 'CONV008', senderId: 'EMW001', content: 'It is our privilege to serve the community Jean. Your gratitude means a lot to our whole team. The most important thing now is to get your asthma properly managed so we do not have a repeat episode. Follow through with Dr. Ramsaran, address those home triggers, and carry a full inhaler at all times. Take good care of yourself.', readAt: null, createdAt: new Date('2024-12-15T15:20:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV009 — DOC001 ↔ PHARM001: Drug interaction coordination (Dec 16–17, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG148', conversationId: 'CONV009', senderId: 'DOC001', content: 'Good morning. I need your input on a medication issue for one of my patients, Mrs. Emma Thompson — PAT001. She is currently on Metformin 500mg twice daily and Lisinopril 10mg daily. I am considering adding a statin for her elevated LDL of 138 mg/dL. What would you recommend?', readAt: read('2024-12-16T07:55:00'), createdAt: new Date('2024-12-16T07:40:00') },
    { id: 'MSG149', conversationId: 'CONV009', senderId: 'PHARM001', content: 'Good morning Dr. Johnson. I am familiar with Mrs. Thompson — she fills her prescriptions with us. For a diabetic patient with an LDL of 138, I would suggest Atorvastatin 20mg as a first-line option. It pairs well with Metformin and there are no significant drug-drug interactions between the three medications.', readAt: read('2024-12-16T08:20:00'), createdAt: new Date('2024-12-16T08:00:00') },
    { id: 'MSG150', conversationId: 'CONV009', senderId: 'DOC001', content: 'That was my thinking as well. I also wanted to flag something — she recently inquired about starting berberine supplements. She mentioned a friend recommended it. I advised against it given the Metformin, but could you note that in her pharmacy profile in case she tries to purchase it elsewhere?', readAt: read('2024-12-16T08:40:00'), createdAt: new Date('2024-12-16T08:25:00') },
    { id: 'MSG151', conversationId: 'CONV009', senderId: 'PHARM001', content: 'She actually asked me about berberine last week and I flagged the same concern — the additive hypoglycemic risk with Metformin. I have already placed an interaction alert on her profile. Good to know you have counselled her as well. Double reinforcement helps with supplement-curious patients.', readAt: read('2024-12-16T09:05:00'), createdAt: new Date('2024-12-16T08:45:00') },
    { id: 'MSG152', conversationId: 'CONV009', senderId: 'DOC001', content: 'Excellent, thank you. Now regarding the Atorvastatin — should it be taken at a specific time of day? I recall there is some debate about statins and evening dosing. And are there any dietary considerations she should know about?', readAt: read('2024-12-16T09:30:00'), createdAt: new Date('2024-12-16T09:10:00') },
    { id: 'MSG153', conversationId: 'CONV009', senderId: 'PHARM001', content: 'Atorvastatin has a long half-life of about 14 hours, so it can be taken at any time of day unlike shorter-acting statins like Simvastatin which must be taken in the evening. For simplicity, I would suggest she takes it with her evening meal alongside the Metformin. The main dietary consideration is to avoid large quantities of grapefruit juice, as it inhibits CYP3A4 and can increase statin blood levels significantly.', readAt: read('2024-12-16T10:00:00'), createdAt: new Date('2024-12-16T09:35:00') },
    { id: 'MSG154', conversationId: 'CONV009', senderId: 'DOC001', content: 'Good point about the grapefruit. I will mention that in her prescription instructions. What about monitoring? Should I check liver enzymes before starting and at follow-up?', readAt: read('2024-12-16T10:25:00'), createdAt: new Date('2024-12-16T10:05:00') },
    { id: 'MSG155', conversationId: 'CONV009', senderId: 'PHARM001', content: 'Current guidelines recommend baseline liver function tests before initiating statin therapy. Her most recent ALT and AST from last week were both normal at 24 and 22 respectively, so you have a good baseline. Routine repeat liver testing is no longer universally recommended unless the patient develops symptoms — muscle pain, fatigue, dark urine, or jaundice. CK levels should be checked only if she reports myalgia.', readAt: read('2024-12-16T10:50:00'), createdAt: new Date('2024-12-16T10:30:00') },
    { id: 'MSG156', conversationId: 'CONV009', senderId: 'DOC001', content: 'Noted. Speaking of myalgia, what is the incidence of muscle-related side effects with Atorvastatin 20mg? I want to set realistic expectations for the patient.', readAt: read('2024-12-16T14:20:00'), createdAt: new Date('2024-12-16T14:00:00') },
    { id: 'MSG157', conversationId: 'CONV009', senderId: 'PHARM001', content: 'Muscle symptoms occur in roughly 5 to 10% of statin users, though many of these cases are not directly caused by the medication when tested in blinded trials. True statin-induced myopathy with elevated CK is rare, less than 0.1%. If she does develop muscle pain, the first step would be to rule out other causes like hypothyroidism or vitamin D deficiency before discontinuing. Switching to Rosuvastatin or using alternate-day dosing are options if intolerance occurs.', readAt: read('2024-12-16T14:50:00'), createdAt: new Date('2024-12-16T14:25:00') },
    { id: 'MSG158', conversationId: 'CONV009', senderId: 'DOC001', content: 'Very helpful. I will check her vitamin D level at the next blood draw since deficiency is common here in Mauritius despite the sun — many patients avoid sun exposure. One more question: she also takes paracetamol occasionally for headaches. Any concern with the triple combination?', readAt: read('2024-12-17T07:50:00'), createdAt: new Date('2024-12-17T07:30:00') },
    { id: 'MSG159', conversationId: 'CONV009', senderId: 'PHARM001', content: 'Occasional paracetamol up to 2g daily is fine with this combination. I would caution against regular use of NSAIDs like ibuprofen though — they can reduce the effectiveness of Lisinopril and may affect kidney function when combined with an ACE inhibitor, especially in a diabetic patient. If she needs regular pain management, paracetamol remains the safest option.', readAt: read('2024-12-17T08:15:00'), createdAt: new Date('2024-12-17T07:55:00') },
    { id: 'MSG160', conversationId: 'CONV009', senderId: 'DOC001', content: 'I will make sure to note that in her chart — no NSAIDs. I will write the Atorvastatin 20mg prescription today and send it electronically. Can you ensure the pharmacist on duty reviews it against her full medication list before dispensing?', readAt: read('2024-12-17T08:40:00'), createdAt: new Date('2024-12-17T08:20:00') },
    { id: 'MSG161', conversationId: 'CONV009', senderId: 'PHARM001', content: 'Absolutely, every new prescription goes through a full interaction check before dispensing. I will personally review it when it comes through. I will also provide her with a medication information leaflet about the statin and counsel her on what side effects to watch for when she picks it up.', readAt: read('2024-12-17T09:00:00'), createdAt: new Date('2024-12-17T08:45:00') },
    { id: 'MSG162', conversationId: 'CONV009', senderId: 'DOC001', content: 'Perfect. Let us plan to reassess her lipid panel in 8 weeks to see the response to Atorvastatin. If LDL does not drop below 100, we may need to increase to 40mg. Thank you for the thorough consultation — this kind of doctor-pharmacist collaboration is invaluable.', readAt: null, createdAt: new Date('2024-12-17T09:10:00') },
    { id: 'MSG163', conversationId: 'CONV009', senderId: 'PHARM001', content: 'Agreed, 8 weeks is the right interval to measure the statin effect. I will flag her profile for the follow-up. Thank you Dr. Johnson — always happy to collaborate on optimizing patient care. Have a good day.', readAt: null, createdAt: new Date('2024-12-17T09:25:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV010 — PAT001 ↔ INS001: Insurance claim inquiry (Dec 18–19, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG164', conversationId: 'CONV010', senderId: 'PAT001', content: 'Good morning. I am reaching out about an insurance claim I submitted two weeks ago for a consultation with my endocrinologist on November 28th. The claim reference is CLM-2024-1847. I have not received any update and wanted to check on the status.', readAt: read('2024-12-18T10:25:00'), createdAt: new Date('2024-12-18T10:10:00') },
    { id: 'MSG165', conversationId: 'CONV010', senderId: 'INS001', content: 'Good morning Emma. Let me pull up your claim. I can see CLM-2024-1847 — it is for a specialist consultation totalling Rs 3,500. The claim is currently in processing. I see a note that we requested additional documentation, specifically the referral letter from your primary care physician. Was that submitted?', readAt: read('2024-12-18T10:50:00'), createdAt: new Date('2024-12-18T10:30:00') },
    { id: 'MSG166', conversationId: 'CONV010', senderId: 'PAT001', content: 'I was not aware a referral letter was needed. Dr. Johnson referred me verbally during our consultation. Does it need to be a formal written referral? I did not receive any notification about missing documentation.', readAt: read('2024-12-18T11:10:00'), createdAt: new Date('2024-12-18T10:55:00') },
    { id: 'MSG167', conversationId: 'CONV010', senderId: 'INS001', content: 'I apologize for the communication gap — the notification should have been sent to your registered email on December 5th. Let me check. It appears it was sent but may have gone to spam. Under your plan, specialist consultations require a written referral from your primary care doctor for the claim to be processed. The referral just needs to state the reason for the specialist visit.', readAt: read('2024-12-18T11:35:00'), createdAt: new Date('2024-12-18T11:15:00') },
    { id: 'MSG168', conversationId: 'CONV010', senderId: 'PAT001', content: 'I will check my spam folder. Can I ask Dr. Johnson to issue the referral letter retroactively? He did recommend the endocrinologist visit during our November consultation. Also, what exactly should the letter include?', readAt: read('2024-12-18T11:55:00'), createdAt: new Date('2024-12-18T11:40:00') },
    { id: 'MSG169', conversationId: 'CONV010', senderId: 'INS001', content: 'Yes, a retroactive referral letter is acceptable as long as it is dated on or before the specialist visit date. The letter should include: the patient name, the referring doctor details, the reason for referral, the specialist name, and the date of the original recommendation. Once we receive it, we can process the claim within 5 business days.', readAt: read('2024-12-18T12:20:00'), createdAt: new Date('2024-12-18T12:00:00') },
    { id: 'MSG170', conversationId: 'CONV010', senderId: 'PAT001', content: 'I will contact Dr. Johnson today to get that letter. While I have you, I also wanted to ask about my upcoming lab tests. My doctor ordered a full metabolic panel and HbA1c for March. Are those covered under my plan?', readAt: read('2024-12-18T14:20:00'), createdAt: new Date('2024-12-18T14:00:00') },
    { id: 'MSG171', conversationId: 'CONV010', senderId: 'INS001', content: 'Let me check your coverage details. You are on the HealthPlus Premium plan. Under this plan, routine diagnostic blood work is covered at 80% up to Rs 15,000 per year. Looking at your claims history, you have used Rs 4,200 of that allowance this year. A full metabolic panel and HbA1c typically costs around Rs 2,500 to Rs 3,000, so you have sufficient remaining coverage.', readAt: read('2024-12-18T14:50:00'), createdAt: new Date('2024-12-18T14:25:00') },
    { id: 'MSG172', conversationId: 'CONV010', senderId: 'PAT001', content: 'Good, so I will only pay 20% out of pocket for the lab work. That is manageable. One more question — I have been considering physiotherapy for some back pain. Is that covered and do I need a referral for that as well?', readAt: read('2024-12-18T15:15:00'), createdAt: new Date('2024-12-18T15:00:00') },
    { id: 'MSG173', conversationId: 'CONV010', senderId: 'INS001', content: 'Physiotherapy is covered under your plan at 70% up to 12 sessions per year. Yes, you will need a referral from your primary care doctor or a specialist. The referral should specify the condition being treated and the recommended number of sessions. You have not used any physiotherapy sessions this year so you have the full 12 available.', readAt: read('2024-12-18T15:40:00'), createdAt: new Date('2024-12-18T15:20:00') },
    { id: 'MSG174', conversationId: 'CONV010', senderId: 'PAT001', content: 'That is very helpful. I will discuss the physiotherapy with Dr. Johnson during my next visit and get a referral if he agrees it would help. How do I submit claims for physiotherapy — is it the same process as other claims?', readAt: read('2024-12-19T08:30:00'), createdAt: new Date('2024-12-19T08:10:00') },
    { id: 'MSG175', conversationId: 'CONV010', senderId: 'INS001', content: 'The process is the same. You can submit claims through the Healthwyz app, by email, or in person at our office. You will need the physiotherapist invoice, the referral letter, and a treatment summary for each session. For convenience, many physiotherapy clinics can submit claims directly on your behalf if you provide your insurance member number.', readAt: read('2024-12-19T09:00:00'), createdAt: new Date('2024-12-19T08:35:00') },
    { id: 'MSG176', conversationId: 'CONV010', senderId: 'PAT001', content: 'Direct submission sounds much easier. I will look for a clinic that offers that. Can you also confirm when my policy renews? I want to make sure I use my remaining benefits before the year resets.', readAt: read('2024-12-19T09:25:00'), createdAt: new Date('2024-12-19T09:05:00') },
    { id: 'MSG177', conversationId: 'CONV010', senderId: 'INS001', content: 'Your HealthPlus Premium plan renews on April 1st each year. So you have until March 31st to use this year\'s benefits. Currently, you still have: Rs 10,800 remaining on lab work, all 12 physiotherapy sessions, and Rs 45,000 remaining on specialist consultations. I would recommend scheduling any pending appointments before the renewal date.', readAt: read('2024-12-19T09:50:00'), createdAt: new Date('2024-12-19T09:30:00') },
    { id: 'MSG178', conversationId: 'CONV010', senderId: 'PAT001', content: 'That is a great reminder. I will get my lab work and physiotherapy sorted before March. Thank you for being so thorough and helpful with everything. I will send the referral letter from Dr. Johnson as soon as I have it.', readAt: null, createdAt: new Date('2024-12-19T10:00:00') },
    { id: 'MSG179', conversationId: 'CONV010', senderId: 'INS001', content: 'You are welcome Emma. Once you submit the referral letter, I will personally ensure your claim CLM-2024-1847 is fast-tracked. Do not hesitate to reach out if you have any other questions about your coverage. Have a wonderful day!', readAt: null, createdAt: new Date('2024-12-19T10:15:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV011 — PAT003 ↔ DOC002: Pediatric health check (Dec 20–21, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG180', conversationId: 'CONV011', senderId: 'PAT003', content: 'Good morning Dr. Patel. I hope I am not bothering you. I wanted to discuss my daughter Amira\'s upcoming vaccinations. She turned 4 last month and I am not sure which vaccines are due. I also have some concerns about her growth that I would like to bring up.', readAt: read('2024-12-20T08:55:00'), createdAt: new Date('2024-12-20T08:40:00') },
    { id: 'MSG181', conversationId: 'CONV011', senderId: 'DOC002', content: 'Good morning Aisha, not a bother at all. At age 4, Amira is due for several important boosters. Let me check her vaccination record. She should be due for the DTaP booster — that is diphtheria, tetanus, and pertussis — the IPV polio booster, and the MMR second dose if she has not had it yet. Let me pull up her file.', readAt: read('2024-12-20T09:20:00'), createdAt: new Date('2024-12-20T09:00:00') },
    { id: 'MSG182', conversationId: 'CONV011', senderId: 'PAT003', content: 'She had the MMR second dose at 18 months, so that one is done. But I am not sure about the DTaP and polio boosters. Her vaccination booklet shows the last DTaP was at 18 months as well. Is she overdue?', readAt: read('2024-12-20T09:45:00'), createdAt: new Date('2024-12-20T09:25:00') },
    { id: 'MSG183', conversationId: 'CONV011', senderId: 'DOC002', content: 'The DTaP and IPV boosters are typically given between ages 4 and 6, so she is right on schedule. It is best to get them done before she starts primary school, as most schools in Mauritius require proof of vaccination. I would recommend scheduling these for her next visit. We can administer both on the same day.', readAt: read('2024-12-20T10:10:00'), createdAt: new Date('2024-12-20T09:50:00') },
    { id: 'MSG184', conversationId: 'CONV011', senderId: 'PAT003', content: 'That is a relief — I was worried we had missed the window. She starts pre-primary in January so the timing is good. Now about my growth concerns. Compared to other children her age, Amira seems quite small. She is 95 cm tall and weighs 13.5 kg. Is that within normal range?', readAt: read('2024-12-20T10:35:00'), createdAt: new Date('2024-12-20T10:15:00') },
    { id: 'MSG185', conversationId: 'CONV011', senderId: 'DOC002', content: 'Let me plot those measurements on the growth chart. At 4 years old, 95 cm puts Amira around the 10th percentile for height, and 13.5 kg is approximately the 15th percentile for weight. While these are on the lower end, what matters most is whether she is following her own growth curve consistently. Do you have her measurements from her 3-year checkup?', readAt: read('2024-12-20T11:00:00'), createdAt: new Date('2024-12-20T10:40:00') },
    { id: 'MSG186', conversationId: 'CONV011', senderId: 'PAT003', content: 'At her 3-year checkup she was 88 cm and 12.1 kg. I have the numbers written in her health booklet. She has always been on the smaller side. Both my husband and I are not very tall — I am 155 cm and he is 168 cm.', readAt: read('2024-12-20T11:25:00'), createdAt: new Date('2024-12-20T11:05:00') },
    { id: 'MSG187', conversationId: 'CONV011', senderId: 'DOC002', content: 'That growth velocity is actually reassuring. She grew 7 cm in one year, which is within the expected 5 to 8 cm per year for her age. Given both parents\' heights, her genetic potential predicts a shorter stature and she is tracking consistently along her own percentile curve. This is not concerning — she is simply a petite child following her genetic blueprint.', readAt: read('2024-12-20T11:50:00'), createdAt: new Date('2024-12-20T11:30:00') },
    { id: 'MSG188', conversationId: 'CONV011', senderId: 'PAT003', content: 'That makes me feel much better. Some of the other mothers at playgroup have commented on her size and it made me anxious. What about her diet? She is a picky eater and refuses most vegetables. I worry she is not getting enough nutrients.', readAt: read('2024-12-20T14:20:00'), createdAt: new Date('2024-12-20T14:00:00') },
    { id: 'MSG189', conversationId: 'CONV011', senderId: 'DOC002', content: 'Picky eating is extremely common at age 4 — it is actually a developmental phase. The key is to keep offering variety without pressure. Research shows it can take 15 to 20 exposures to a new food before a child accepts it. Try involving her in food preparation, offering vegetables in fun shapes, or blending them into sauces. What does a typical day of eating look like for her?', readAt: read('2024-12-20T14:50:00'), createdAt: new Date('2024-12-20T14:25:00') },
    { id: 'MSG190', conversationId: 'CONV011', senderId: 'PAT003', content: 'Breakfast is usually oat porridge with banana. Lunch is rice with dal or sometimes chicken — she picks around the vegetables. For snack she has fruit or rice crackers. Dinner is similar to lunch. She drinks oat milk because she is lactose sensitive. She does eat eggs which is good.', readAt: read('2024-12-20T15:15:00'), createdAt: new Date('2024-12-20T14:55:00') },
    { id: 'MSG191', conversationId: 'CONV011', senderId: 'DOC002', content: 'Her diet is actually better than many 4-year-olds I see. The oat porridge, eggs, chicken, and dal provide good protein. The banana and fruits cover some vitamins. Since she drinks oat milk rather than cow milk, make sure it is fortified with calcium and vitamin D. I would also recommend a children\'s multivitamin with iron as a safety net, especially given her picky vegetable intake.', readAt: read('2024-12-20T15:40:00'), createdAt: new Date('2024-12-20T15:20:00') },
    { id: 'MSG192', conversationId: 'CONV011', senderId: 'PAT003', content: 'Yes, the oat milk is fortified. I will start a multivitamin — any specific brand you recommend? Also, should I be concerned about her iron levels given that she does not eat much red meat?', readAt: read('2024-12-21T08:30:00'), createdAt: new Date('2024-12-21T08:10:00') },
    { id: 'MSG193', conversationId: 'CONV011', senderId: 'DOC002', content: 'Any reputable children\'s multivitamin with iron will do — Centrum Kids or Wellkid are both available at pharmacies here. For iron specifically, eggs and dal are good plant-based sources. You can boost iron absorption by pairing these with vitamin C-rich foods like orange slices or tomato. If you are concerned, we can check her haemoglobin level when she comes in for vaccinations.', readAt: read('2024-12-21T09:00:00'), createdAt: new Date('2024-12-21T08:35:00') },
    { id: 'MSG194', conversationId: 'CONV011', senderId: 'PAT003', content: 'That would put my mind at ease. Let us check her haemoglobin. I also wanted to mention that she has been having occasional stomach aches after meals. It happens maybe two or three times a week. Could it be related to the lactose sensitivity?', readAt: read('2024-12-21T09:30:00'), createdAt: new Date('2024-12-21T09:10:00') },
    { id: 'MSG195', conversationId: 'CONV011', senderId: 'DOC002', content: 'It could be. Even small amounts of dairy like cheese can cause discomfort in lactose-sensitive children. However, stomach aches in 4-year-olds can also be related to constipation, anxiety, or simply eating too quickly. How are her bowel movements? Is she regular?', readAt: read('2024-12-21T10:00:00'), createdAt: new Date('2024-12-21T09:35:00') },
    { id: 'MSG196', conversationId: 'CONV011', senderId: 'PAT003', content: 'She goes once daily, usually in the morning. It seems normal. She does eat quite fast though — she always wants to finish quickly to go play. The stomach aches tend to happen about 30 minutes after eating and usually resolve on their own within an hour.', readAt: read('2024-12-21T14:20:00'), createdAt: new Date('2024-12-21T14:00:00') },
    { id: 'MSG197', conversationId: 'CONV011', senderId: 'DOC002', content: 'The timing — 30 minutes post-meal — is consistent with either lactose intolerance or simply eating too fast and swallowing air. Try encouraging slower eating by sitting at the table together and making mealtimes relaxed. You could also try eliminating all dairy for two weeks to see if the stomach aches resolve. That would tell us definitively if lactose is the culprit.', readAt: read('2024-12-21T14:50:00'), createdAt: new Date('2024-12-21T14:25:00') },
    { id: 'MSG198', conversationId: 'CONV011', senderId: 'PAT003', content: 'That is a great idea. I will try the dairy-free trial and keep a food diary to track the stomach aches. When should I bring her in for the vaccinations and blood test? I would like to get it all done in one visit if possible.', readAt: read('2024-12-21T15:15:00'), createdAt: new Date('2024-12-21T15:00:00') },
    { id: 'MSG199', conversationId: 'CONV011', senderId: 'DOC002', content: 'We can do everything in one visit — DTaP booster, IPV booster, and a finger-prick haemoglobin test. I have availability on January 8th at 9:30 AM, which is perfect timing before she starts school. Bring her vaccination booklet, the food diary if you have started it, and the list of any symptoms from the dairy-free trial.', readAt: null, createdAt: new Date('2024-12-21T15:25:00') },
    { id: 'MSG200', conversationId: 'CONV011', senderId: 'PAT003', content: 'January 8th at 9:30 AM is perfect. I will start the dairy-free trial and food diary tomorrow. Thank you so much Dr. Patel — you have addressed all of my concerns and I feel much more confident about her health. See you in January!', readAt: null, createdAt: new Date('2024-12-21T15:40:00') },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONV012 — NUR001 ↔ NAN001: Nursing-childcare coordination (Dec 22–23, 2 days)
    // ═══════════════════════════════════════════════════════════════════════════
    { id: 'MSG201', conversationId: 'CONV012', senderId: 'NUR001', content: 'Good morning. I am reaching out because we have a patient, Mrs. Devi, who was admitted yesterday for a planned knee replacement surgery. She is a single mother with a 6-year-old son, Arjun, and has no family nearby to help with childcare during her hospital stay. She asked if we could coordinate something through the platform.', readAt: read('2024-12-22T07:25:00'), createdAt: new Date('2024-12-22T07:10:00') },
    { id: 'MSG202', conversationId: 'CONV012', senderId: 'NAN001', content: 'Good morning. Thank you for reaching out. I am happy to help. How long is Mrs. Devi expected to be in the hospital? And does Arjun have school during this period or is he on holiday break?', readAt: read('2024-12-22T07:50:00'), createdAt: new Date('2024-12-22T07:30:00') },
    { id: 'MSG203', conversationId: 'CONV012', senderId: 'NUR001', content: 'The surgery is scheduled for tomorrow morning. Typical hospital stay for a knee replacement is 3 to 5 days, so she expects to be discharged by December 26th or 27th. Schools are on Christmas break so Arjun will be home all day. She will also need help at home for the first week after discharge as her mobility will be very limited.', readAt: read('2024-12-22T08:15:00'), createdAt: new Date('2024-12-22T07:55:00') },
    { id: 'MSG204', conversationId: 'CONV012', senderId: 'NAN001', content: 'I can cover from tomorrow through December 31st if needed — that would cover both the hospital stay and the initial recovery period at home. What are Arjun\'s needs? Any medical conditions, allergies, or special requirements I should be aware of?', readAt: read('2024-12-22T08:40:00'), createdAt: new Date('2024-12-22T08:20:00') },
    { id: 'MSG205', conversationId: 'CONV012', senderId: 'NUR001', content: 'He is a healthy boy with no known allergies or medical conditions. He does have mild ADHD and takes Ritalin 10mg each morning with breakfast. Mrs. Devi will prepare his medication in a labelled pill box before her surgery. He is generally well-behaved but can be quite energetic and needs structured activities to stay focused.', readAt: read('2024-12-22T09:05:00'), createdAt: new Date('2024-12-22T08:45:00') },
    { id: 'MSG206', conversationId: 'CONV012', senderId: 'NAN001', content: 'I have experience with ADHD children so that is not a concern. I will plan structured activities — arts and crafts, outdoor play in the morning when the medication is most effective, and quieter activities in the afternoon. What time does he take his Ritalin and does he have any dietary preferences?', readAt: read('2024-12-22T09:30:00'), createdAt: new Date('2024-12-22T09:10:00') },
    { id: 'MSG207', conversationId: 'CONV012', senderId: 'NUR001', content: 'He takes it at 7:30 AM with breakfast. The medication can reduce appetite at lunchtime, so Mrs. Devi suggests offering smaller, frequent meals rather than one large lunch. He loves pasta, chicken nuggets, and fruit. He is not fond of spicy food. Bedtime is 8 PM and he usually needs a story to settle down.', readAt: read('2024-12-22T10:00:00'), createdAt: new Date('2024-12-22T09:35:00') },
    { id: 'MSG208', conversationId: 'CONV012', senderId: 'NAN001', content: 'That is very helpful. I will prepare a meal plan with his preferences in mind. Now regarding the logistics — will I be staying at Mrs. Devi\'s home overnight or is this daytime care only? And is there a spare key or will Arjun be there to let me in?', readAt: read('2024-12-22T10:25:00'), createdAt: new Date('2024-12-22T10:05:00') },
    { id: 'MSG209', conversationId: 'CONV012', senderId: 'NUR001', content: 'Mrs. Devi is requesting overnight care since she will be in the hospital and there is no one else. She has a spare room prepared for you. The neighbour, Mr. Lutchmun, has a spare key and has been informed. He is also listed as the emergency contact along with Mrs. Devi\'s phone number. I will share all contact details with you.', readAt: read('2024-12-22T10:50:00'), createdAt: new Date('2024-12-22T10:30:00') },
    { id: 'MSG210', conversationId: 'CONV012', senderId: 'NAN001', content: 'Overnight care is not a problem. I will pack a bag. One important question — how does Arjun feel about his mother being in the hospital? Is he anxious? I want to be prepared to address his emotional needs as well.', readAt: read('2024-12-22T14:20:00'), createdAt: new Date('2024-12-22T14:00:00') },
    { id: 'MSG211', conversationId: 'CONV012', senderId: 'NUR001', content: 'Mrs. Devi says he understands that mummy needs to fix her knee and that she will be back soon. He seems mostly okay but asked if he could video call her every day. I have already arranged for Mrs. Devi to have her phone accessible post-surgery for daily video calls. Morning and evening calls of about 10 minutes each should reassure him.', readAt: read('2024-12-22T14:50:00'), createdAt: new Date('2024-12-22T14:25:00') },
    { id: 'MSG212', conversationId: 'CONV012', senderId: 'NAN001', content: 'Daily video calls are a great idea. I will help him with those. I can also have him draw pictures or make cards for his mother that we can bring when visiting. Would Mrs. Devi like us to visit her in the hospital? It might help Arjun to see that she is doing well.', readAt: read('2024-12-22T15:15:00'), createdAt: new Date('2024-12-22T14:55:00') },
    { id: 'MSG213', conversationId: 'CONV012', senderId: 'NUR001', content: 'A short visit on December 25th would be lovely — visiting hours are 10 AM to 12 PM and 3 PM to 5 PM. I would suggest the afternoon slot on Christmas Day as Mrs. Devi should be more alert and mobile by then. She will be in the orthopaedic ward, Room 12. Just keep the visit to about 30 minutes so she can rest.', readAt: read('2024-12-22T15:40:00'), createdAt: new Date('2024-12-22T15:20:00') },
    { id: 'MSG214', conversationId: 'CONV012', senderId: 'NAN001', content: 'Perfect, we will visit Christmas afternoon. I will make sure Arjun has a card ready for her. Now regarding the transition home — what will Mrs. Devi\'s care needs be when she is discharged? I want to understand so I can help coordinate between her recovery and Arjun\'s care.', readAt: read('2024-12-23T07:30:00'), createdAt: new Date('2024-12-23T07:10:00') },
    { id: 'MSG215', conversationId: 'CONV012', senderId: 'NUR001', content: 'Post-discharge, Mrs. Devi will be on crutches and will need help with mobility, bathing, and household tasks. She will have physiotherapy exercises to do three times daily. She will be on pain medication that may cause drowsiness. The main priority at home will be making sure Arjun is supervised while she rests, and helping with meals and light housekeeping.', readAt: read('2024-12-23T08:00:00'), createdAt: new Date('2024-12-23T07:35:00') },
    { id: 'MSG216', conversationId: 'CONV012', senderId: 'NAN001', content: 'I can manage all of that. I will prepare meals for both Mrs. Devi and Arjun, keep the house tidy, supervise Arjun\'s play and medication, and remind Mrs. Devi about her physio exercises. Should I also help her with wound care or is that something a nurse will handle?', readAt: read('2024-12-23T08:30:00'), createdAt: new Date('2024-12-23T08:05:00') },
    { id: 'MSG217', conversationId: 'CONV012', senderId: 'NUR001', content: 'I will arrange for a visiting nurse to come on days 2, 4, and 7 after discharge for wound assessment and dressing changes. You should not need to handle the wound care directly. However, please monitor for signs of infection — increasing redness, swelling, warmth around the knee, or fever above 38 degrees. If any of those occur, contact me immediately.', readAt: read('2024-12-23T09:00:00'), createdAt: new Date('2024-12-23T08:35:00') },
    { id: 'MSG218', conversationId: 'CONV012', senderId: 'NAN001', content: 'Understood. I will keep a close eye on her recovery and contact you if anything seems off. To summarize my understanding: I arrive tomorrow morning at 7 AM, collect the key from Mr. Lutchmun, manage Arjun\'s care and medication through the hospital stay and first week of recovery, facilitate daily video calls, visit on Christmas afternoon, and assist with household needs once Mrs. Devi is home.', readAt: read('2024-12-23T09:25:00'), createdAt: new Date('2024-12-23T09:05:00') },
    { id: 'MSG219', conversationId: 'CONV012', senderId: 'NUR001', content: 'That is a perfect summary. I will send you Mr. Lutchmun\'s contact details, the home address, and Mrs. Devi\'s phone number after this conversation. Mrs. Devi is very grateful and relieved to know Arjun will be in good hands. Thank you for being flexible during the holiday period.', readAt: null, createdAt: new Date('2024-12-23T09:30:00') },
    { id: 'MSG220', conversationId: 'CONV012', senderId: 'NAN001', content: 'It is my pleasure. Children need stability during stressful times and I will make sure Arjun feels safe and cared for. Please tell Mrs. Devi not to worry about a thing — she should focus entirely on her surgery and recovery. I will keep you updated on how things are going. Have a good day and I will see you at the ward tomorrow.', readAt: null, createdAt: new Date('2024-12-23T09:45:00') },
  ]

  await prisma.message.createMany({
    data: messages,
    skipDuplicates: true,
  })

  console.log(`  Seeded ${conversations.length} conversations, ${participants.length} participants, ${messages.length} messages`)
}
