import { PrismaClient } from '@prisma/client'

export async function seedProviderReviews(prisma: PrismaClient) {
  const reviews = [
    // ── Doctor Reviews ──────────────────────────────────────────────────────
    {
      providerUserId: 'DOC001',
      reviewerUserId: 'PAT001',
      providerType: 'DOCTOR',
      rating: 5,
      comment: 'Dr. Johnson is incredibly thorough with her diabetes management approach. She explained my insulin regimen clearly and followed up personally after adjusting my medication. My blood sugar levels have been much more stable since I started seeing her.',
      verified: true,
      helpfulCount: 12,
      response: 'Thank you, Emma! I am glad to hear your levels have stabilised. Keep up with the dietary adjustments and we will review at your next appointment.',
      respondedAt: new Date('2025-12-20'),
      createdAt: new Date('2025-12-15'),
    },
    {
      providerUserId: 'DOC001',
      reviewerUserId: 'PAT003',
      providerType: 'DOCTOR',
      rating: 5,
      comment: 'Excellent endocrinologist. She took the time to explain the connection between my thyroid condition and fatigue. Very professional and caring. The video consultation was seamless.',
      verified: true,
      helpfulCount: 8,
      response: null,
      respondedAt: null,
      createdAt: new Date('2026-01-10'),
    },
    {
      providerUserId: 'DOC001',
      reviewerUserId: 'PAT002',
      providerType: 'DOCTOR',
      rating: 4,
      comment: 'Very knowledgeable doctor. Wait time was a bit long but the consultation itself was worth it. She really listens to your concerns.',
      verified: true,
      helpfulCount: 5,
      response: 'Thank you for your feedback, Jean. We are working on reducing wait times with our new scheduling system.',
      respondedAt: new Date('2026-01-22'),
      createdAt: new Date('2026-01-18'),
    },
    {
      providerUserId: 'DOC002',
      reviewerUserId: 'PAT004',
      providerType: 'DOCTOR',
      rating: 5,
      comment: 'Dr. Patel is our family physician and has been wonderful. He is patient, explains things in plain language, and always makes sure we understand the treatment plan. Highly recommend for families.',
      verified: true,
      helpfulCount: 15,
      response: 'Thank you for trusting me with your family\'s health. It is always a pleasure seeing you all.',
      respondedAt: new Date('2025-11-08'),
      createdAt: new Date('2025-11-05'),
    },
    {
      providerUserId: 'DOC002',
      reviewerUserId: 'PAT001',
      providerType: 'DOCTOR',
      rating: 4,
      comment: 'Good GP who takes a holistic approach to care. He caught a vitamin deficiency that others had missed. The home visit option is very convenient.',
      verified: true,
      helpfulCount: 3,
      response: null,
      respondedAt: null,
      createdAt: new Date('2026-02-01'),
    },
    {
      providerUserId: 'DOC003',
      reviewerUserId: 'PAT005',
      providerType: 'DOCTOR',
      rating: 5,
      comment: 'Dr. Dupont is an exceptional cardiologist. After my heart scare, she ran comprehensive tests and created a detailed recovery plan. Her expertise gave me peace of mind. I feel much healthier now.',
      verified: true,
      helpfulCount: 20,
      response: 'I am so glad you are feeling better! Remember to keep up with the exercise plan and we will do your follow-up echocardiogram next month.',
      respondedAt: new Date('2026-02-18'),
      createdAt: new Date('2026-02-14'),
    },
    {
      providerUserId: 'DOC003',
      reviewerUserId: 'PAT002',
      providerType: 'DOCTOR',
      rating: 3,
      comment: 'Competent cardiologist but the clinic was quite busy. The consultation felt a bit rushed. Would have liked more time to discuss lifestyle changes.',
      verified: false,
      helpfulCount: 2,
      response: null,
      respondedAt: null,
      createdAt: new Date('2026-01-25'),
    },

    // ── Nurse Reviews ────────────────────────────────────────────────────────
    {
      providerUserId: 'NUR001',
      reviewerUserId: 'PAT001',
      providerType: 'NURSE',
      rating: 5,
      comment: 'Nurse Priya provided excellent wound care at home after my surgery. She was gentle, professional, and very reassuring. She also taught my family how to change the dressing properly.',
      verified: true,
      helpfulCount: 9,
      response: 'Thank you, Emma! Proper wound care education is so important for recovery. Glad your healing went well.',
      respondedAt: new Date('2025-12-10'),
      createdAt: new Date('2025-12-05'),
    },
    {
      providerUserId: 'NUR001',
      reviewerUserId: 'PAT003',
      providerType: 'NURSE',
      rating: 4,
      comment: 'Very professional and caring nurse. She monitored my mother\'s blood pressure over several home visits and coordinated well with the doctor. Reliable and punctual.',
      verified: true,
      helpfulCount: 6,
      response: null,
      respondedAt: null,
      createdAt: new Date('2026-01-15'),
    },
    {
      providerUserId: 'NUR001',
      reviewerUserId: 'PAT005',
      providerType: 'NURSE',
      rating: 5,
      comment: 'Priya is an outstanding nurse. She managed my post-cardiac care with incredible attention to detail. Her geriatric care experience really shows. I felt safe and well looked after.',
      verified: true,
      helpfulCount: 11,
      response: 'Thank you so much! Taking care of your recovery was a priority and I am happy to see how well you are doing.',
      respondedAt: new Date('2026-02-25'),
      createdAt: new Date('2026-02-20'),
    },
    {
      providerUserId: 'NUR002',
      reviewerUserId: 'PAT002',
      providerType: 'NURSE',
      rating: 4,
      comment: 'Sophie was very helpful during my recovery from a respiratory infection. She explained the medication schedule clearly and checked on me regularly through the app.',
      verified: true,
      helpfulCount: 4,
      response: null,
      respondedAt: null,
      createdAt: new Date('2026-01-28'),
    },
    {
      providerUserId: 'NUR002',
      reviewerUserId: 'PAT004',
      providerType: 'NURSE',
      rating: 5,
      comment: 'Excellent pediatric nursing care for our toddler. Sophie was patient and gentle, and made the whole experience less stressful for both us and our child. Highly recommended for families with young children.',
      verified: true,
      helpfulCount: 7,
      response: 'It was a pleasure caring for your little one! Children can be nervous around medical professionals, so I always try to make it a positive experience.',
      respondedAt: new Date('2026-02-12'),
      createdAt: new Date('2026-02-08'),
    },

    // ── Nanny Reviews ────────────────────────────────────────────────────────
    {
      providerUserId: 'NAN001',
      reviewerUserId: 'PAT001',
      providerType: 'NANNY',
      rating: 5,
      comment: 'Anita has been wonderful with our children. She is certified in first aid and child development which gives us great peace of mind. The kids absolutely love her and always look forward to her visits.',
      verified: true,
      helpfulCount: 14,
      response: 'Thank you, Emma! Your children are delightful and I truly enjoy spending time with them. Their curiosity makes every session fun!',
      respondedAt: new Date('2025-11-20'),
      createdAt: new Date('2025-11-15'),
    },
    {
      providerUserId: 'NAN001',
      reviewerUserId: 'PAT004',
      providerType: 'NANNY',
      rating: 5,
      comment: 'Anita is incredibly reliable and experienced. She handled our newborn with such confidence and taught us several soothing techniques. Her CPR certification also gives us extra confidence.',
      verified: true,
      helpfulCount: 10,
      response: null,
      respondedAt: null,
      createdAt: new Date('2026-01-05'),
    },
    {
      providerUserId: 'NAN001',
      reviewerUserId: 'PAT002',
      providerType: 'NANNY',
      rating: 4,
      comment: 'Great nanny service. Anita engaged our son in educational activities and was very attentive to his dietary needs. Only giving 4 stars because scheduling can sometimes be tricky.',
      verified: true,
      helpfulCount: 3,
      response: 'Thank you for your feedback, Jean. I am working on improving my scheduling flexibility. Glad your son enjoyed the activities!',
      respondedAt: new Date('2026-02-05'),
      createdAt: new Date('2026-02-01'),
    },
    {
      providerUserId: 'NAN002',
      reviewerUserId: 'PAT003',
      providerType: 'NANNY',
      rating: 5,
      comment: 'Claire is an exceptional childcare professional. She created a wonderful daily routine for our twins and always keeps them engaged with age-appropriate activities. Very organised and communicative.',
      verified: true,
      helpfulCount: 8,
      response: 'Working with your twins is such a joy! They are making great developmental progress and I am happy to be part of their journey.',
      respondedAt: new Date('2026-02-15'),
      createdAt: new Date('2026-02-10'),
    },
    {
      providerUserId: 'NAN002',
      reviewerUserId: 'PAT005',
      providerType: 'NANNY',
      rating: 4,
      comment: 'Very caring and professional nanny. Claire looked after our grandchildren during a family event and they had a wonderful time. She is creative with activities and very safety-conscious.',
      verified: true,
      helpfulCount: 5,
      response: null,
      respondedAt: null,
      createdAt: new Date('2026-01-20'),
    },
  ]

  for (const review of reviews) {
    await prisma.providerReview.create({
      data: review,
    })
  }

  console.log(`  Seeded ${reviews.length} provider reviews`)
}
